=== Adonis-Dulaurent/XML_TEI_PCF/ReunionPcfEncodage/ReunionPCF.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT TEI (teiHeader, text)>

<!-- TEI Header -->
<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title, author)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publicationStmt (authority, date ,availability)>
<!ELEMENT authority (#PCDATA)>
<!ELEMENT availability (licence)>
<!ELEMENT licence (#PCDATA) >
<!ELEMENT date (#PCDATA)>

<!ELEMENT sourceDesc (msDesc)>
<!ELEMENT msDesc (msIdentifier)>
<!ELEMENT msIdentifier (country, settlement, repository, idno)>
<!ELEMENT country (#PCDATA)>
<!ATTLIST country key NMTOKEN #IMPLIED>
<!ELEMENT settlement (#PCDATA) >
<!ATTLIST settlement ref CDATA #IMPLIED>
<!ATTLIST settlement type NMTOKEN #IMPLIED>
<!ELEMENT repository (#PCDATA) >
<!ATTLIST repository xml:lang NMTOKEN #REQUIRED>
<!ELEMENT idno (#PCDATA)>

<!-- Body of the text TEI-->

<!ELEMENT text (body)>
<!ELEMENT body (div1+)>

<!-- Document structure -->
<!ELEMENT div1 (head, (div2 | decisions)*, p+)>
<!ELEMENT div2 (#PCDATA) >
<!ATTLIST div2 type (document | decisions) #REQUIRED>

<!-- Decision structure -->
<!ELEMENT decisions (head, p+)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT p (#PCDATA)>

<!ELEMENT back (listPerson,listPlace,listEvent)>

<!-- Names, and roles -->
<!ELEMENT listPerson (person)+>
<!ELEMENT person (persName, birth?, death?) >
<!ATTLIST person xml:id ID #REQUIRED>
<!ELEMENT persName (#PCDATA|roleName|forename|surname)*>
<!ATTLIST persName ref IDREF #IMPLIED>
<!ATTLIST persName xml:lang NMTOKEN #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT roleName (#PCDATA)>
<!ELEMENT birth (date)>
<!ELEMENT death (date)>

<!-- listplace -->
<!ELEMENT listPlace (place)+>
<!ELEMENT place (placeName)>
<!ATTLIST place xml:id ID #REQUIRED>
<!ELEMENT placeName (#PCDATA|adress|settlement)*>
<!ATTLIST placeName ref IDREF #IMPLIED>
<!ATTLIST placeName xml:lang NMTOKEN #IMPLIED>
<!ELEMENT adress (street,settlement, country) >
<!ELEMENT street (#PCDATA|num)*>
<!ELEMENT num (#PCDATA) >

<!-- Subject -->
<!ELEMENT listEvent (event)+ >
<!ATTLIST event xml:id ID #REQUIRED>
<!ATTLIST event ref IDREF #REQUIRED >
<!ELEMENT event (eventName, note)>
<!ELEMENT eventName (#PCDATA)>
<!ELEMENT note (#PCDATA)>

=== Adonis-Dulaurent/XML_TEI_PCF/ReunionPcfEncodage/ReunionPCF_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!DOCTYPE TEI SYSTEM "ReunionPCF.dtd">
<TEI xml:lang="en" xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Title</title>
            <author></author>
         </titleStmt>
         <publicationStmt>
            <authority></authority>
            <date></date>
            <availability>
               <licence></licence>
            </availability>
         </publicationStmt>
         <sourceDesc>
            <msDesc>
               <msIdentifier>
                  <country>France</country>
                  <settlement></settlement>
                  <repository></repository>
                  <idno></idno>
               </msIdentifier>
            </msDesc>
         </sourceDesc>
      </fileDesc>
  </teiHeader>
  <text>
      <body>
         <div1 type="document">
            <head></head>
            <div2 type="decisions">
                  <head></head>
                  <p></p>
            </div2>
         </div1>
      </body>
 
  <back> 
     <listPerson>
      <person xml:id="person1">
         <persName>
            <forename>forename</forename>
            <surname>surname</surname>
            <roleName>roleName</roleName>
         </persName>
         <birth></birth>
         <death></death>
      </person>
      <person xml:id="person2">
         <persName>
            <forename>forename</forename>
            <surname>surname</surname>
            <roleName>roleName</roleName>
         </persName>
         <birth></birth>
         <death></death>
      </person>
   </listPerson>
   <listPlace>
      <place xml:id="place1">
         <placeName>place</placeName>
      </place>
      <place xml:id="place2">
         <placeName>place</placeName>
      </place>
   </listPlace>
   <listEvent>
      <event xml:id="event1">
         <eventName></eventName>
         <note>text</note>
      </event>
      <event xml:id="event2">
         <eventName></eventName>
         <note>text</note>
      </event>
   </listEvent>
  </back> 
 </text>
</TEI>
